### ISSUE TITLE
Update website 

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#10]
- [x] Syllabus
- [x] [Lecture list](https://docs.google.com/document/d/1pIc6uAoF-O-d3ojt1hwODnZGJpaAf--4mrL9a4lT8IY/edit)
- [x] HW instructions - see #14
- [x] Resources

**Comment by yoavram** [comment]
resources: 
- http://opentechschool.github.io/python-data-intro/
- http://blog.yhathq.com/: 
  - http://blog.yhathq.com/posts/aggregating-and-plotting-time-series-in-python.html
  - http://blog.yhathq.com/posts/11-python-libraries-you-might-not-know.html
- [Think Stats](http://greenteapress.com/thinkstats/)
- [Pandas Tips and Tricks](http://www.bigdataexaminer.com/14-best-python-pandas-features/)

**Comment by yoavram** [comment]
The website is now working on py4life.yoavram.com.
We could create an organization called py4life and transfer the repo to it and then the website could be
py4life.github.io or py4life.github.io/tau2015 and then we won't have the _yoavram_ in it.
Any thoughts, @soungalo ?

**Comment by soungalo** [comment]
Let's do it. I have created an organization and invited you. Not sure what to do next...

**Comment by yoavram** [comment]
I'll transfer the repo to the organization and set the URLs.
Then both of us will have to change the git remotes.
I'll update you.

**Comment by yoavram** [comment]
done
