### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#13]
Check if this is good, I think it is:
https://piazza.com/class/hwg2heycbck775

**Comment by soungalo** [comment]
Created Piazza forum. 
https://piazza.com/class/i5zd9s048q96j1
Still have to:
- [ ] Enroll students (before start of semester)
- [x] Add link from website to forum

**Comment by yoavram** [comment]
~~You dont enroll, they sign up.~~ You are right, they should enroll, I remember now that I emailed piazza support last time to ask them to allow students to enroll because I didn't have an email roster.
As for link, attaching to #10.

**Comment by yoavram** [comment]
Sorry it's #10

**Comment by yoavram** [comment]
Added link, added emails to piazze for enrollment.
