### ISSUE TITLE
Duplicate the repository 

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#15]
Duplicate the repo https://help.github.com/articles/duplicating-a-repository/
and make it private and give @yoavram collaboration permission.
Then we can have the HW solutions there and make PR to the public one when publishing solutions.

**Comment by soungalo** [comment]
Created a mirror repo and invited @yoavram  as collaborator.

**Comment by yoavram** [comment]
Thanks. I added there a `HOWTO.md` with instructions but I think it's too much overhead, I'll think of a better way to do it.
