### ISSUE TITLE
Add some points to lecture 4

### ISSUE THREAD

**Issue by soungalo** [yoavram/Py4Life#18]
- [x] Using readline() method with a while loop
- [ ] using next(f) to skip lines (e.g. headers line)

**Comment by yoavram** [comment]
I think `readline` is useful but I'm not sure about using `while` with reading from files.
About `next` - this is totally redundent when already teaching `readline` and is really just an implementation for using files as generators if I'm not mistaken.
Let's try to keep the file idioms to a minium - `for line in f`, `f.read()`, `f.readline()` - I think this should be enough for 95% of applications.

**Comment by soungalo** [comment]
I think while, combined with readline() is useful when parsing more complex files (added it to the lecture). I agree about the next() being redundant.
