### ISSUE TITLE
Piazza forum setup

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#23]
Go over the posts that the forum started with and see if there is anything interesting we should do there.

**Comment by soungalo** [comment]
Some good points:
1. Tell the students that the only way to ask questions should be through the forum (not mails, unless it's something private).
2. Use the 'note' option to create announcements, instead\in addition to moodle, once everyone has enrolled.
3. Use the 'good question' and 'good answer' options. Maybe even promise a bonus to the student with the highest number of good posts...?
4. Create a welcome post.
5. Use tags (#) and links to other questions (@), mark duplicate questions etc.

**Comment by yoavram** [comment]
1. add to lecture 1 logistics
2. we shouldn't replicate. either moodle or piazza.
3. sure. but promising a bonus - I don't like. there is enough credit in reputation.
4. yes.
5. sure
   sue 1 and 5 should be discussed in lecture 1 I think.

**Comment by soungalo** [comment]
1. OK. Let's talk about what we need to tell them.
2. So let's go with Piazza, but since not everyone is enrolled, we'll also use moodle if we need to send more stuff before the first class.
3. OK, never mind.
4. I'll do it next week.
5. OK

**Comment by soungalo** [comment]
Just sent a welcome message through the forum.
