### ISSUE TITLE
BioPython lecture takeaways

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#28]

**Comment by soungalo** [comment]
There were some difficulties installing Biopython, so:
- Ask the computer lab guy to install it in the beginning of the term.
- Tell students who use their own laptops to install it in advance.
- Use conda (not PIP)
- Make sure numpy is installed and updated before trying to install

Running BLAST on the NCBI server (using the NCBIWWW.qblast method) sucks. Either create a local server beforehand and run queries on it, or just skip BLAST and teach something else. Maybe put more time on using the Entrez module.
