### ISSUE TITLE
Exam preparation

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#30]
- [x] Add course logo etc. to the exam
- [ ] Publish exam example
- [x] Make sure the exam is in notebook format 3 - `cat exam_example.ipynb  | grep nbformat`
  - [ ] If not in nbformat 3, change format - `ipython nbconvert --to notebook --nbformat 3 XXX.ipynb` creates `XXX.v3.ipynb`.
- [x] Check that the exam works on the lab computers 
- [x] Ask someone to go over the exam  
- [x] Check that all lab computers work and that all packages are installed.

**Comment by soungalo** [comment]
Text for the website:

The example exam resembles the type and level of the questions in the real exams. You have to answer all questions, in the dedicated boxes within the notebook. Download the notebook and insert your solutions. In the real exam, you will submit them just like you did with homework during the semester.
The expected outputs are included (and will also be included in the real exams), and you have to replicate them with your code.
Make sure you follow the instructions and generate the outputs exactly as described.
We recommend that you try to solve the example, and only then look at the solutions.
You are welcome to discuss the example exam in the course forum.
Good luck!

**Comment by yoavram** [comment]
I think this should be in the example exam, not on the website.
