### ISSUE TITLE
Homework - rest of course

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#7]

**Comment by yoavram** [comment]
@soungalo which weeks do we need homework for?

**Comment by soungalo** [comment]
We need three more:
- [x] lecture 6 - ~~debugging and~~ Biopython (LG)
- [x] lecture 7 - data analysis & plotting (YR)
- [x] lecture 10 -  stochastic processes & population dynamics (YR)

**Comment by yoavram** [comment]
Ok so I'll do most of it -- you'll do the biopython part.

**Comment by yoavram** [comment]
I added dates for the homework to the website.

**Comment by yoavram** [comment]
@soungalo please review hw7

**Comment by soungalo** [comment]
Reviewed HW7.

**Comment by yoavram** [comment]
Updated with text. Plz have a look.
